version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t nginx_test99:v1 .
  post_build:
    commands:
      - echo Build completed
